services:
  elastic_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ELASTIC_PASSWORD=changeme
      - discovery.type=single-node
      # Abaixo estou desabilitando o ssl para que não de erro ao tentar acessar de http
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    depends_on:
      - elastic_search
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic_search:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana_system

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  
  vai-tomano:
    build: .
    ports:
      - 3002:3002

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - 3001:3000
  
  locust:
    image: locustio/locust
    container_name: locust
    volumes:
      - ./:/mnt/locust
    ports:
      - 8089:8089
    command: ['-f', '/mnt/locust/locustfile.py']